// <auto-generated />
using System;
using Consumer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Consumer.Migrations
{
    [DbContext(typeof(PiplineDbContext))]
    partial class PiplineDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Consumer.Models.StationInformationDto", b =>
                {
                    b.Property<string>("StationId")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<double>("Lat")
                        .HasColumnType("double");

                    b.Property<double>("Lon")
                        .HasColumnType("double");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("StationId");

                    b.ToTable("StationInfo");
                });

            modelBuilder.Entity("Consumer.Models.VehicleTypeDto", b =>
                {
                    b.Property<string>("VehicleTypeId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FormFactor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double?>("MaxRangeMeters")
                        .HasColumnType("double");

                    b.Property<string>("PropulsionType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("VehicleTypeId");

                    b.ToTable("VehicleTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
